@startuml

left to right direction

skinparam Shadowing false
skinparam Monochrome true
skinparam PackageStyle rectangle

actor "A Picories User" as user
actor "A Follower" as follower

package "Picture" {
  usecase "Share picture" as UC1
  usecase "Like picture" as UC2
  usecase "Delete picture" as UC3
  usecase "Comment on a picture" as UC4
}

package "Live stream" {
  usecase "Start live stream" as UC5
  usecase "Join live stream" as UC6
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5
follower ---> UC4
follower ---> UC2
follower ---> UC6


@enduml
